# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MOon Lap
email: lux0425@gmail.com
description: > # this means to ignore newlines until "baseurl:"  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mooonlee.github.io" # the base hostname & protocol for your site
github_username:  MOONLEE
timezone: Asia/Seoul 



# Build settings
markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge


plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]


keep_files: [assets, files]
author: lux0425@gamil.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets